# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# Create publisher
# Publisher.create(name: 'Эксмо')
# Publisher.create(name: 'АСТ')
# Publisher.create(name: 'Азбука')


# Create books
Book.create(title: 'Конек-горбунок', publisher: Publisher.find(1))
Book.create(title: 'Корни неба', publisher: Publisher.find(1))
Book.create(title: 'Оно', publisher: Publisher.find(2))
Book.create(title: 'Зеленый Фонарь. Возрождение', publisher: Publisher.find(3))
Book.create(title: 'Шантарам. Том 1', publisher: Publisher.find(3))
Book.create(title: 'Шантарам. Том 2', publisher: Publisher.find(3))

Shop.create(name: 'Читай-город')
Shop.create(name: 'Ozon')
Shop.create(name: 'Amazon')

Shop::Item.create(book: Book.find(1), shop: Shop.find(1))
Shop::Item.create(book: Book.find(1), shop: Shop.find(1))
Shop::Item.create(book: Book.find(3), shop: Shop.find(3))
Shop::Item.create(book: Book.find(2), shop: Shop.find(2))
Shop::Item.create(book: Book.find(3), shop: Shop.find(3))
Shop::Item.create(book: Book.find(4), shop: Shop.find(2))
Shop::Item.create(book: Book.find(5), shop: Shop.find(2))
Shop::Item.create(book: Book.find(4), shop: Shop.find(1))
Shop::Item.create(book: Book.find(3), shop: Shop.find(3))
Shop::Item.create(book: Book.find(4), shop: Shop.find(3))
Shop::Item.create(book: Book.find(1), shop: Shop.find(3))
Shop::Item.create(book: Book.find(6), shop: Shop.find(1))
Shop::Item.create(book: Book.find(6), shop: Shop.find(1))
Shop::Item.create(book: Book.find(5), shop: Shop.find(1))
Shop::Item.create(book: Book.find(1), shop: Shop.find(1))
Shop::Item.create(book: Book.find(1), shop: Shop.find(1))
Shop::Item.create(book: Book.find(3), shop: Shop.find(1))
Shop::Item.create(book: Book.find(3), shop: Shop.find(3))
Shop::Item.create(book: Book.find(2), shop: Shop.find(2))
Shop::Item.create(book: Book.find(3), shop: Shop.find(3))
Shop::Item.create(book: Book.find(4), shop: Shop.find(2))
Shop::Item.create(book: Book.find(5), shop: Shop.find(2))
Shop::Item.create(book: Book.find(4), shop: Shop.find(1))
Shop::Item.create(book: Book.find(3), shop: Shop.find(3))
Shop::Item.create(book: Book.find(4), shop: Shop.find(3))
Shop::Item.create(book: Book.find(1), shop: Shop.find(3))
Shop::Item.create(book: Book.find(6), shop: Shop.find(1))
Shop::Item.create(book: Book.find(6), shop: Shop.find(1))
Shop::Item.create(book: Book.find(5), shop: Shop.find(1))
Shop::Item.create(book: Book.find(1), shop: Shop.find(1))
Shop::Item.create(book: Book.find(1), shop: Shop.find(1))
Shop::Item.create(book: Book.find(3), shop: Shop.find(1))
Shop::Item.create(book: Book.find(3), shop: Shop.find(3))
Shop::Item.create(book: Book.find(2), shop: Shop.find(2))
Shop::Item.create(book: Book.find(3), shop: Shop.find(3))
Shop::Item.create(book: Book.find(4), shop: Shop.find(2))
Shop::Item.create(book: Book.find(5), shop: Shop.find(2))
Shop::Item.create(book: Book.find(4), shop: Shop.find(1))
Shop::Item.create(book: Book.find(3), shop: Shop.find(3))
Shop::Item.create(book: Book.find(4), shop: Shop.find(3))
Shop::Item.create(book: Book.find(1), shop: Shop.find(3))
Shop::Item.create(book: Book.find(6), shop: Shop.find(1))
Shop::Item.create(book: Book.find(6), shop: Shop.find(1))
Shop::Item.create(book: Book.find(5), shop: Shop.find(1))
Shop::Item.create(book: Book.find(1), shop: Shop.find(1))
Shop::Item.create(book: Book.find(1), shop: Shop.find(1))
Shop::Item.create(book: Book.find(3), shop: Shop.find(1))
Shop::Item.create(book: Book.find(3), shop: Shop.find(3))
Shop::Item.create(book: Book.find(2), shop: Shop.find(2))
Shop::Item.create(book: Book.find(3), shop: Shop.find(3))
Shop::Item.create(book: Book.find(4), shop: Shop.find(2))
Shop::Item.create(book: Book.find(5), shop: Shop.find(2))
Shop::Item.create(book: Book.find(4), shop: Shop.find(1))
Shop::Item.create(book: Book.find(3), shop: Shop.find(3))
Shop::Item.create(book: Book.find(4), shop: Shop.find(3))
Shop::Item.create(book: Book.find(1), shop: Shop.find(3))
Shop::Item.create(book: Book.find(6), shop: Shop.find(1))
Shop::Item.create(book: Book.find(6), shop: Shop.find(1))
Shop::Item.create(book: Book.find(5), shop: Shop.find(1))
Shop::Item.create(book: Book.find(3), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(2), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(1), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(3), shop: Shop.find(2), state: 'sold')
Shop::Item.create(book: Book.find(4), shop: Shop.find(2), state: 'sold')
Shop::Item.create(book: Book.find(1), shop: Shop.find(3), state: 'sold')
Shop::Item.create(book: Book.find(5), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(6), shop: Shop.find(3), state: 'sold')
Shop::Item.create(book: Book.find(6), shop: Shop.find(2), state: 'sold')
Shop::Item.create(book: Book.find(4), shop: Shop.find(3), state: 'sold')
Shop::Item.create(book: Book.find(3), shop: Shop.find(3), state: 'sold')
Shop::Item.create(book: Book.find(1), shop: Shop.find(2), state: 'sold')
Shop::Item.create(book: Book.find(4), shop: Shop.find(2), state: 'sold')
Shop::Item.create(book: Book.find(3), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(1), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(3), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(2), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(1), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(3), shop: Shop.find(2), state: 'sold')
Shop::Item.create(book: Book.find(4), shop: Shop.find(2), state: 'sold')
Shop::Item.create(book: Book.find(1), shop: Shop.find(3), state: 'sold')
Shop::Item.create(book: Book.find(5), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(6), shop: Shop.find(3), state: 'sold')
Shop::Item.create(book: Book.find(6), shop: Shop.find(2), state: 'sold')
Shop::Item.create(book: Book.find(4), shop: Shop.find(3), state: 'sold')
Shop::Item.create(book: Book.find(3), shop: Shop.find(3), state: 'sold')
Shop::Item.create(book: Book.find(1), shop: Shop.find(2), state: 'sold')
Shop::Item.create(book: Book.find(4), shop: Shop.find(2), state: 'sold')
Shop::Item.create(book: Book.find(3), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(1), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(3), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(2), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(1), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(3), shop: Shop.find(2), state: 'sold')
Shop::Item.create(book: Book.find(4), shop: Shop.find(2), state: 'sold')
Shop::Item.create(book: Book.find(1), shop: Shop.find(3), state: 'sold')
Shop::Item.create(book: Book.find(5), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(6), shop: Shop.find(3), state: 'sold')
Shop::Item.create(book: Book.find(6), shop: Shop.find(2), state: 'sold')
Shop::Item.create(book: Book.find(4), shop: Shop.find(3), state: 'sold')
Shop::Item.create(book: Book.find(3), shop: Shop.find(3), state: 'sold')
Shop::Item.create(book: Book.find(1), shop: Shop.find(2), state: 'sold')
Shop::Item.create(book: Book.find(4), shop: Shop.find(2), state: 'sold')
Shop::Item.create(book: Book.find(3), shop: Shop.find(1), state: 'sold')
Shop::Item.create(book: Book.find(1), shop: Shop.find(1), state: 'sold')